In [ ]:
# Import required libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
# Load the wine dataset
wine = load_wine()

In [ ]:
#Extract the First 100 Features
X = pd.DataFrame(data = wine.data[:100,:], columns = wine.feature_names)
X.head(100)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0     14.23        1.71  2.43               15.6      127.0           2.80   
1     13.20        1.78  2.14               11.2      100.0           2.65   
2     13.16        2.36  2.67               18.6      101.0           2.80   
3     14.37        1.95  2.50               16.8      113.0           3.85   
4     13.24        2.59  2.87               21.0      118.0           2.80   
..      ...         ...   ...                ...        ...            ...   
95    12.47        1.52  2.20               19.0      162.0           2.50   
96    11.81        2.12  2.74               21.5      134.0           1.60   
97    12.29        1.41  1.98               16.0       85.0           2.55   
98    12.37        1.07  2.10               18.5       88.0           3.52   
99    12.29        3.17  2.21               18.0       88.0           2.85   

    flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0         3.06                  0.28             2.29             5.64  1.04   
1         2.76                  0.26             1.28             4.38  1.05   
2         3.24                  0.30             2.81             5.68  1.03   
3         3.49                  0.24             2.18             7.80  0.86   
4         2.69                  0.39             1.82             4.32  1.04   
..         ...                   ...              ...              ...   ...   
95        2.27                  0.32             3.28             2.60  1.16   
96        0.99                  0.14             1.56             2.50  0.95   
97        2.50                  0.29             1.77             2.90  1.23   
98        3.75                  0.24             1.95             4.50  1.04   
99        2.99                  0.45             2.81             2.30  1.42   

    od280/od315_of_diluted_wines  proline  
0                           3.92   1065.0  
1                           3.40   1050.0  
2                           3.17   1185.0  
3                           3.45   1480.0  
4                           2.93    735.0  
..                           ...      ...  
95                          2.63    937.0  
96                          2.26    625.0  
97                          2.74    428.0  
98                          2.77    660.0  
99                          2.83    406.0  

[100 rows x 13 columns]

In [7]:
# Convert the data to a pandas DataFrame
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.DataFrame(wine.target, columns=['target'])

In [8]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)# Create and train the MLP Classifier
mlp = MLPClassifier(hidden_layer_sizes=(100,), max_iter=300, alpha=0.0001, solver='adam', random_state=42)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(max_iter=300, random_state=42)

In [10]:
# Make predictions on the test set
y_pred = mlp.predict(X_test)

In [11]:
# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


In [12]:
# Generate the Confusion Matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]
